language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh ./Lab01Solution/Lab01Solution.sln
  - ./build.sh ./Lab02Solution/Lab02Solution.sln
#  - ./build.sh ./Lab03Solution/Lab03Solution.sln # WPF
  - ./build.sh ./Lab04Solution/Lab04Solution.sln
#  - ./build.sh ./Lab05Solution/Lab05Solution.sln # WCF
notifications:
  email: false
