//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab01ClassLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab01ClassLibrary.Resources.ErrorsRes", typeof(ErrorsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obliczania średniej.
        /// </summary>
        public static string CalculateAverage {
            get {
                return ResourceManager.GetString("CalculateAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obliczania odchylenia.
        /// </summary>
        public static string CalculateDeviation {
            get {
                return ResourceManager.GetString("CalculateDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deserializacji danych.
        /// </summary>
        public static string DeserializeData {
            get {
                return ResourceManager.GetString("DeserializeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pobierania danych z generatora.
        /// </summary>
        public static string LoadDataFromGenerator {
            get {
                return ResourceManager.GetString("LoadDataFromGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odczytu danych z pliku.
        /// </summary>
        public static string ReadData {
            get {
                return ResourceManager.GetString("ReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serializacji danych.
        /// </summary>
        public static string SerializeData {
            get {
                return ResourceManager.GetString("SerializeData", resourceCulture);
            }
        }
    }
}
