//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab01ClassLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab01ClassLibrary.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas {0}. Więcej informacji w obiekcie &apos;innerException&apos;.
        /// </summary>
        public static string ErrorOccuredSeeInnerException {
            get {
                return ResourceManager.GetString("ErrorOccuredSeeInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizowany plik &apos;{0}&apos; zawiera dane, które nie można skonwertować do typu &apos;{1}&apos; .
        /// </summary>
        public static string FileContainsInvalidData {
            get {
                return ResourceManager.GetString("FileContainsInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa pliku nie została ustawiona.
        /// </summary>
        public static string FileNameNotSet {
            get {
                return ResourceManager.GetString("FileNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik o nazwie &apos;{0}&apos; nie istnieje..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator nie został ustawiony. Przed użyciem analizatora ustaw generator metodą &apos;SetGenerator(IGenerator generator)&apos;.
        /// </summary>
        public static string GeneratorNotSet {
            get {
                return ResourceManager.GetString("GeneratorNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ parametru &apos;{0}&apos; nie jest obsługiwany. Klasa &apos;{1}&apos; wymaga parametru typu &apos;{2}&apos;.
        /// </summary>
        public static string InvalidParamType {
            get {
                return ResourceManager.GetString("InvalidParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametr nie został ustawiony. Przed użyciem generatora ustaw parametr metodą &apos;PassParameter(object obj)&apos;.
        /// </summary>
        public static string ParameterNotSet {
            get {
                return ResourceManager.GetString("ParameterNotSet", resourceCulture);
            }
        }
    }
}
